import { FooterComp } from './Components/Footer'
import './globals.css'
import { Inter } from 'next/font/google'
import { AuthProvider } from './context/auth-context'
import { NavBar } from './Components/navbar/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  
  title: 'CountryPay',
  description: 'Generated by create next app',
  favicon: 'https://res.cloudinary.com/dhb9rdaoc/image/upload/v1694012039/o73c9yspzssdvpkqy7dv.svg'

}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
     <head>
            <title>{metadata.title}</title>
            <meta name="description" content={metadata.description} />
            <link rel="icon" type="image/x-icon" href="https://res.cloudinary.com/dhb9rdaoc/image/upload/v1694012039/o73c9yspzssdvpkqy7dv.svg"/>

        </head>
      <body className={inter.className}>
      <AuthProvider>
        <NavBar/>
      
      <main className='h-full ' >  
      {children}
      
      </main>
      
      <FooterComp/>
      </AuthProvider>
      </body>
    </html>
  )
}
