import React from 'react'

export const metadata = {
  
    title: 'CountryPay - Dashboard',
    description: 'Generated by create next app',

  }
  

function LayoutDashoard({children}) {
  return (
    <div>
        {/* <head>
            <title>{metadata.title}</title>
            <meta name="description" content={metadata.description} />
    
        </head> */}

        <div className='bg-Morado/R200 md:min-h-[75vh]'>
        {children}

        </div>
    </div>
  )
}

export default LayoutDashoard